import pandas as pd
new_data = [
{'text' : 'i have so many assignments that i want to die','label' : 0},
{'text' : "I'm really frustrated with my friend; I want to avoid them.",'label' : 0},
{'text' :  "You're so stupid, why do you even bother participating in discussions?","label" : 1},
{'text' : "I disagree with your opinion; let's discuss it.",'label' : 0},
{'text' : "Everyone should avoid talking to you; you're a loser.","label" : 1},
{'text' : "I don't appreciate your behavior; it's affecting the team negatively.",'label' : 0},
{'text' : "Nobody likes you; you're a burden to everyone around you.",'label' : 1},
{'text' : "I feel hurt by the comments you made; let's try to resolve this peacefully.",'label' : 0},
{'text' : "You're so ugly; I can't believe anyone would want to be friends with you.",'label' : 1},
{'text' :  "I don't agree with your perspective, but I respect your right to have different opinions.",'label' : 0},
{'text' : "I heard a rumor about you, and it's not something you'd want others to know.",'label' : 1},
{'text': "I don't agree with your choices, but I respect your right to make them.",'label' : 0},
{'text' :  "You're a failure; you'll never amount to anything.",'label' : 1},
{'text' : "I find your behavior annoying, but I'd rather discuss it than resort to insults.",'label' : 0},
{'text' : "Why are you even here? No one wants you around.",'label' : 1},
{'text' : "Let's find a solution together; we don't have to agree, but we can work it out.",'label' : 0},
{'text' :  "You're such a loser; I can't believe anyone would be friends with you.",'label' : 1},
{'text' : "I felt hurt when you ignored my message; let's talk about what happened.",'label' : 0},
{'text' : "Your ideas are so stupid; no one should take you seriously.","label" : 1},
{'text' : "I appreciate our differences; it's what makes our discussions interesting.","label" : 0},
{'text' : "Everyone talks about how much they can't stand you.","label" : 1},
{'text': "I'm really frustrated with your incompetence.", 'label': 1},
{'text': "Your ideas are so stupid; no one should take you seriously.", 'label': 1},
{'text': "I appreciate your effort, but your work is a joke.", 'label': 1},
{'text': "You're such a burden; nobody wants to deal with your problems.", 'label': 1},
{'text': "I've noticed a pattern in your behavior; let's address it together.", 'label': 0},
{'text': "Your sense of humor is terrible; no one laughs at your jokes.", 'label': 1},
{'text': "I value our friendship, but I need some space right now.", 'label': 0},
{'text': "You're always so forgettable; no one cares what you do.", 'label': 1},
{'text': "I admire your dedication to your work; let's find a way to collaborate more effectively.", 'label': 0},
{'text': "You're always making mistakes; I don't know why anyone would trust you.", 'label': 1},
{'text': "You're such a loser; no one wants to be associated with you.", 'label': 1},
{'text': "I feel hurt by your comments; let's discuss and find a resolution.", 'label': 0},
{'text': "You're so unoriginal; I've seen people like you a hundred times.", 'label': 1},
{'text': "I've noticed a mistake in your work; let's work together to correct it.", 'label': 0},
{'text': "You're always so defensive; can't you take criticism?", 'label': 1},
{'text': "I appreciate your effort, but I think we can improve the project with some adjustments.", 'label': 0},
{'text': "You're so unreliable; I can't believe I trusted you.", 'label': 1},
{'text': "I think we have different perspectives on this issue; let's explore each other's viewpoints.", 'label': 0},
{'text': "You're such a disappointment; I expected more from you.", 'label': 1},
{'text': "I disagree with your approach, but I respect your right to make it.", 'label': 0},
{'text': "You're always messing things up; it's embarrassing to be associated with you.", 'label': 1},
{'text': "I don't agree with your decision, but I'm open to hearing your reasoning.", 'label': 0},
{'text': "You're so gullible; anyone can manipulate you easily.", 'label': 1},
{'text': "I've observed some challenges in our teamwork; let's find solutions together.", 'label': 0},
{'text': "You're such a disappointment; I expected more from you.", 'label': 1},
{'text': "I feel like there's tension between us; can we talk and find a resolution?", 'label': 0},
{'text': "You're always making mistakes; it's embarrassing.", 'label': 1},
{'text': "I think there's a miscommunication; let's clarify our perspectives.", 'label': 0},
{'text': "Your work is so sloppy; no wonder you never get recognition.", 'label': 1},
{'text': "I disagree with your perspective, but I'm willing to listen and understand.", 'label': 0},
{'text': "You're such a burden; nobody wants to deal with your problems.", 'label': 1},
{'text': "I've noticed a misunderstanding in our conversation; let's clarify our intentions.", 'label': 0},
{'text': "You're always so boring; no one wants to listen to you.", 'label': 1},
{'text': "I appreciate your effort, but I think we can improve.", 'label': 0},
{'text': "You're always so forgettable; no one cares what you do.", 'label': 1},
{'text': "I disagree with your opinion, but I'm open to discussion.", 'label': 0},
{'text': "You're so naive; it's no wonder people take advantage of you.", 'label': 1},
{'text': "I noticed a mistake in your work; let's work together to correct it.", 'label': 0},
{'text': "You're always so defensive; can't you take criticism?", 'label': 1},
{'text': "I appreciate your effort, but I think we can improve the project with some adjustments.", 'label': 0},
{'text': "You're always so unorganized; I can't rely on you for anything.", 'label': 1},
{'text': "I don't agree with your methods, but I believe we can find a compromise.", 'label': 0},
{'text': "You're such a show-off; nobody likes people like you.", 'label': 1},
{'text': "I noticed a discrepancy in your report; let's review it together.", 'label': 0},
{'text': "Your taste in music is awful; I don't know how anyone can stand it.", 'label': 1},
{'text': "I value our friendship, but I need some time for myself.", 'label': 0},
{'text': "You're always playing the victim; take responsibility for once.", 'label': 1},
{'text': "I appreciate your effort, but there's room for improvement in your work.", 'label': 0},
{'text': "You're such a disappointment; I expected better from someone like you.", 'label': 1},
{'text': "I don't understand your perspective, but I'm open to hearing more about it.", 'label': 0},
{'text': "You're constantly interrupting others; can't you let someone else speak?", 'label': 1},
{'text': "I feel uneasy about your decision; let's discuss it further.", 'label': 0},
{'text': "Your fashion sense is so outdated; you should really update your wardrobe.", 'label': 1},
{'text': "I value our collaboration, but there are areas where we can improve our teamwork.", 'label': 0},
{'text': "You're so forgetful; it's like you can't remember anything.", 'label': 1},
{'text': "I disagree with your perspective, but I respect your right to hold it.", 'label': 0},
{'text': "You're such a pushover; stand up for yourself once in a while.", 'label': 1},
{'text': "I've noticed some misunderstandings; let's work on better communication.", 'label': 0},
{'text': "Your choices are so boring; you need to spice things up in your life.", 'label': 1},
{'text': "I don't like your attitude, but I'm willing to find common ground.", 'label': 0},
{'text': "You're always so indecisive; make up your mind for once.", 'label': 1},
{'text': "I feel uncomfortable with your comments; can we discuss them?", 'label': 0},
{'text': "Your cooking is terrible; I can't believe you enjoy such tasteless food.", 'label': 1},
{'text': "I appreciate your contributions, but there's room for improvement.", 'label': 0},
{'text': "You're so uptight; can't you loosen up a bit?", 'label': 1},
{'text': "I don't agree with your approach, but let's find a compromise.", 'label': 0},
{'text': "Your jokes are so cringe-worthy; nobody finds them funny.", 'label': 1},
{'text': "I've noticed some communication gaps; let's bridge them for better understanding.", 'label': 0},
{'text': "You're always seeking attention; it's annoying.", 'label': 1},
{'text': "I don't understand your reasoning, but I'm open to discussing it.", 'label': 0},
{'text': "Your work lacks originality; it's like you're copying others.", 'label': 1},
{'text': "I appreciate your input, but I think a more thorough analysis is needed.", 'label': 0},
{'text': "You're always taking credit for others' ideas; it's disheartening.", 'label': 1},
{'text': "I've observed a discrepancy in our expectations; let's align them better.", 'label': 0},
{'text': "Your contributions are invaluable, but let's explore new perspectives.", 'label': 0},
{'text': "You're so condescending; can't you communicate without superiority?", 'label': 1},
{'text': "I value our teamwork, but there's room for improvement in our communication.", 'label': 0},
{'text': "You're always undermining others; try acknowledging their strengths.", 'label': 1},
{'text': "I've noticed a lack of clarity in your instructions; let's clarify for better understanding.", 'label': 0},
{'text': "Your constant negativity affects the team morale; let's focus on solutions.", 'label': 1},
{'text': "I don't agree with your strategy, but I'm open to exploring alternatives.", 'label': 0},
{'text': "You're always so judgmental; try understanding others' perspectives.", 'label': 1},
{'text': "I value our collaboration, but we need to address issues for better productivity.", 'label': 0},
{'text': "You're so inflexible; consider other viewpoints for a more inclusive approach.", 'label': 1},
{'text': "I've noticed a lack of attention to detail in your work; let's enhance it together.", 'label': 0},
{'text': "Your constant criticism creates a hostile environment; let's foster positivity.", 'label': 1},
{'text': "I appreciate your dedication, but we need to streamline our processes.", 'label': 0},
{'text': "You're always evading responsibility; it's time to take accountability.", 'label': 1},
{'text': "I've observed a disconnect in our communication; let's bridge the gap.", 'label': 0},
{'text': "Your unwillingness to compromise hinders progress; let's find common ground.", 'label': 1},
{'text': "I don't agree with your decision, but I respect your autonomy in making it.", 'label': 0},
{'text': "You're so indecisive; it's challenging to move forward with uncertainty.", 'label': 1},
{'text': "I value our relationship, but we need to address the issues for a healthier dynamic.", 'label': 0},
{'text': "You're always so defensive; consider constructive feedback for personal growth.", 'label': 1},
{'text': "I've noticed inconsistencies in your work; let's standardize our approach.", 'label': 0},
{'text': "Your lack of empathy creates a toxic atmosphere; let's cultivate compassion.", 'label': 1},
{'text': "I appreciate your unique perspective, but we should strive for consensus.", 'label': 0},
{'text': "You're always evading discussions; let's address issues for a stronger team.", 'label': 1},
{'text': "I've observed a need for better coordination; let's synchronize our efforts.", 'label': 0},
{'text': "Your insistence on control stifles creativity; let's encourage diverse ideas.", 'label': 1}
]

def returnGPTDataframe():
    return pd.DataFrame(new_data)
